--liquibase formatted sql

--changeset Stanislaw|Przemyslaw:3 labels:expansion,tables
CREATE TABLE club
(
    club_id     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(100) NOT NULL,
    description TEXT,
    picture     VARCHAR(255),
    admin_id    BIGINT       NOT NULL
);

CREATE TABLE club_member
(
    club_member_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    club_id        BIGINT  NOT NULL,
    user_id        BIGINT  NOT NULL,
    club_nickname  VARCHAR(30),
    got_accepted   BOOLEAN,
    got_banned     BOOLEAN NOT NULL,
    FOREIGN KEY (club_id) REFERENCES club (club_id),
    FOREIGN KEY (user_id) REFERENCES website_user (user_id)
);

CREATE TABLE club_post
(
    club_post_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    club_id      BIGINT    NOT NULL,
    author_id    BIGINT    NOT NULL,
    content      TEXT      NOT NULL,
    post_date    TIMESTAMP NOT NULL,
    picture      VARCHAR(255),
    FOREIGN KEY (club_id) REFERENCES club (club_id),
    FOREIGN KEY (author_id) REFERENCES club_member (club_member_id)
);

CREATE TABLE club_comment
(
    club_comment_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    club_post_id    BIGINT    NOT NULL,
    author_id       BIGINT    NOT NULL,
    content         TEXT      NOT NULL,
    post_date       TIMESTAMP NOT NULL,
    FOREIGN KEY (club_post_id) REFERENCES club_post (club_post_id),
    FOREIGN KEY (author_id) REFERENCES club_member (club_member_id)
);


CREATE TABLE forum
(
    forum_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    game_id  BIGINT NOT NULL,
    FOREIGN KEY (game_id) REFERENCES game (game_id)
);

CREATE TABLE forum_post
(
    forum_post_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    forum_id      BIGINT    NOT NULL,
    author_id     BIGINT    NOT NULL,
    content       TEXT      NOT NULL,
    post_date     TIMESTAMP NOT NULL,
    picture       VARCHAR(255),
    FOREIGN KEY (forum_id) REFERENCES forum (forum_id),
    FOREIGN KEY (author_id) REFERENCES website_user (user_id)
);

CREATE TABLE forum_comment
(
    forum_comment_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    forum_post_id    BIGINT    NOT NULL,
    author_id        BIGINT    NOT NULL,
    content          TEXT      NOT NULL,
    post_date        TIMESTAMP NOT NULL,
    FOREIGN KEY (forum_post_id) REFERENCES forum_post (forum_post_id),
    FOREIGN KEY (author_id) REFERENCES website_user (user_id)
);


ALTER TABLE club
    ADD CONSTRAINT fk_club_admin FOREIGN KEY (admin_id) REFERENCES website_user (user_id);
ALTER TABLE club_member
    ADD CONSTRAINT unique_club_membership UNIQUE (club_id, user_id);


--changeset Stanislaw:23 labels:expansion,data
--club
INSERT INTO club (name, description, picture, admin_id)
VALUES ('Limbus Enthusiasts', 'A club for fans of Limbus Company to discuss event strategies.', NULL, 4);

INSERT INTO club_member (club_id, user_id, club_nickname, got_accepted, got_banned)
VALUES (1, 4, NULL, true, false),
       (1, 5, 'ZweiClair', true, false);

INSERT INTO club_post (club_id, author_id, content, post_date, picture)
VALUES (1, 1, 'Just completed the RefractionRailway! Took me 98 turns, got lucky with last boss second phase.', '2024-08-12 10:30:00', NULL);

INSERT INTO club_comment (club_post_id, author_id, content, post_date) VALUES
    (1, 2, 'Nice setup! I’m thinking of trying a similar team.', '2024-08-12 12:00:00');

--forum
INSERT INTO forum (forum_id, game_id)
VALUES (1, 1);

INSERT INTO forum_post (forum_id, author_id, content, post_date, picture)
VALUES (1, 5, 'What do you think about the latest update?', '2024-08-13 09:45:00', NULL);

INSERT INTO forum_comment (forum_post_id, author_id, content, post_date)
VALUES (1, 6, 'I think it’s a great, especially with the new characters!', '2024-08-13 10:15:00');

INSERT INTO forum_comment (forum_post_id, author_id, content, post_date)
VALUES (1, 4, 'Meh, was hoping for farmwatch ID', '2024-08-13 10:16:00');


--changeset Stanislaw:24 labels:expansion,schema
ALTER TABLE forum
    ADD COLUMN forum_name VARCHAR(100),
    ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN parent_forum_id BIGINT,
    ADD FOREIGN KEY (parent_forum_id) REFERENCES forum (forum_id);

UPDATE forum
SET forum_name = game.title
FROM game
WHERE forum.game_id = game.game_id;

ALTER TABLE forum
    ALTER COLUMN game_id DROP NOT NULL,
    ALTER COLUMN forum_name SET NOT NULL;

ALTER TABLE forum
    ADD CONSTRAINT unique_forum_name UNIQUE (forum_name);


CREATE TABLE forum_moderator
(
    forum_moderator_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    forum_id           BIGINT NOT NULL,
    moderator_id       BIGINT NOT NULL,
    FOREIGN KEY (forum_id) REFERENCES forum (forum_id),
    FOREIGN KEY (moderator_id) REFERENCES website_user (user_id)
);

ALTER TABLE forum_moderator
    ADD CONSTRAINT unique_forum_moderator UNIQUE (forum_id, moderator_id);

--proper forum hierarchy, missing check for circular reference bc liquibase cant parse trigger with declare
ALTER TABLE forum
    ADD CONSTRAINT check_self_parent
        CHECK (forum_id IS DISTINCT FROM parent_forum_id);

