spring:
  jackson:
    time-zone: Europe/Warsaw
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          show_sql: false
          format_sql: true
          use_sql_comments: false
          ddl-auto: none
          default_auto_commit: false
  liquibase:
    enabled: true
    change-log: db/db.changelog-master.xml
  mail:
    host: localhost
    port: 3025
    username: gamerev@example.com
    password: password123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          filter:
            OncePerRequestFilter: DEBUG
profile:
  pics:
    directory: ../Pictures/profile_pics
game:
  pics:
    directory: ../Pictures/game_pics
throttling:
  enabled: false
  delay: 2000